### PR TITLE
Implement cloudflare provider

### LINKED ISSUE #4: New provider Cloudflare (cf)
I would like to also request Cloudflare support.

### PR DESCRIPTION
**Pull request by danopia**
I'm marking the tested record types starting with this provider: A, AAAA, TXT, CNAME, MX, NS

Fixes #4

### CODE REVIEW

**Comment by danopia** [comment]
This works nicely, except that I'm not really sure how to implement the provider-specific aspect of setting 'proxied'. Still thinking on that.

**Comment by danopia** [comment]
##### external-dns info

Annotation for setting 'proxied': `external-dns.alpha.kubernetes.io/cloudflare-proxied`

Default TTL: 1

Unproxyable records: Wildcards or `LOC`, `MX`, `NS`, `SPF`, `TXT`, `SRV`

links: [docs](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md) [code](https://github.com/kubernetes-sigs/external-dns/blob/8b07536f4ac7a082e4d79e9453d67dd19f1fd876/provider/cloudflare/cloudflare.go)

**Comment by danopia** [comment]
This will need to wait and be rewritten once the refactor #11 is merged

**Comment by samip5** [comment]
I would like to point out that proxing wildcards IS supported on a paid plan.

**Comment by danopia** [comment]
> I would like to point out that proxing wildcards IS supported on a paid plan.

Good info! external-dns is hardcoded to be unable to do that: https://github.com/kubernetes-sigs/external-dns/blob/8b07536f4ac7a082e4d79e9453d67dd19f1fd876/provider/cloudflare/cloudflare.go#L417-L419

The reason it matters here is the create record API doesn't have a 'proxy if possible' flag. Either you require proxying for the record or not, so we need to know when it can be requested per-record.

I don't think I want to check the plan via API so I'll add a `allow_proxied_wildcards = true` option 🤷

**Pull request merged**
